# Generated by Django 6.0.7 on 2026-07-13 12:36

import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('minute', models.CharField(max_length=10)),
                ('penalty', models.BooleanField(default=False)),
                ('own_goal', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(blank=True, null=True)),
                ('round', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('kickoff_time', models.CharField(max_length=20)),
                ('group', models.CharField(blank=True, max_length=20)),
                ('ground', models.CharField(max_length=100)),
                ('team1', models.CharField(max_length=100)),
                ('team2', models.CharField(max_length=100)),
                ('ft_score1', models.IntegerField(blank=True, null=True)),
                ('ft_score2', models.IntegerField(blank=True, null=True)),
                ('ht_score1', models.IntegerField(blank=True, null=True)),
                ('ht_score2', models.IntegerField(blank=True, null=True)),
                ('goals1', django_mongodb_backend.fields.EmbeddedModelArrayField(blank=True, default=list, embedded_model='world_cup.goal')),
                ('goals2', django_mongodb_backend.fields.EmbeddedModelArrayField(blank=True, default=list, embedded_model='world_cup.goal')),
            ],
        ),
    ]
